[supervisord]
nodaemon=true
user=root
loglevel=error
logfile=/dev/null
logfile_maxbytes=0

[program:nextjs]
user=node
directory=/app
command=node server.js
environment=HOSTNAME=0.0.0.0,PORT=3000
killasgroup=true
stopasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
#stderr_logfile=/dev/stderr
#stderr_logfile_maxbytes=0
autorestart=true

[program:nginx]
command=nginx -g 'daemon off;'
killasgroup=true
stopasgroup=true
autorestart=true
