FROM python:3.10-alpine@sha256:3bfac1caa31cc6c0e796b65ba936f320d1e549d80f5ac02c2e4f83a0f04af3aa

ENV USER=watchdog

RUN chmod 1733 /tmp /var/tmp /dev/shm

RUN pip install --no-cache-dir requests debugpy

RUN adduser -D -g "" "$USER" \
 && chown -R root:root "/home/$USER"

COPY --chown=root:watchdog . /home/watchdog/

WORKDIR /home/watchdog
RUN chmod 550 check.py \
 && chmod 440 pw flag_poison

USER watchdog

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "./check.py"]
